config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  devise_for :users

  resources :users, only: [:show, :index]
  resources :quits

end

app/models/quit.rb
# == Schema Information
#
# Table name: quits
#
#  id         :integer          not null, primary key
#  text       :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Quit < ActiveRecord::Base
  belongs_to :user

  validates :text, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable

  has_many :quits

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/quits_controller.rb
class QuitsController < ApplicationController
  def new
    @user = User.find params[:user_id]
    @quit = @user.quits.build
  end

  def create
    @quit = Quit.new quit_params
    if @quit.save
      flash[:success] = 'Created!'
      redirect_to @quit.user
    else
      render 'new'
    end
  end

  def edit
    @quit = Quit.find params[:id]
  end

  def update
    @quit = Quit.find params[:id]
    if @quit.update quit_params
      flash[:success] = 'Updated!'
      redirect_to @quit.user
    else
      render 'edit'
    end
  end

  private

  def quit_params
    params.require(:quit).permit(:user_id, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab9</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header">
      <ul class="nav nav-pills pull-right">
        <li><%= link_to 'Users', users_path %></li>
        <% if user_signed_in? %>
          <li><%= current_user %></li>
          <li><%= link_to 'Logout', destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end  %>
      </ul>
      <h3 class="text-muted">Quitter (Week 9 Lab)</h3>
    </div>
  
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/quits/edit.html.erb
<%= simple_form_for @quit, html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>

app/views/quits/new.html.erb
<%= simple_form_for @quit do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <h3><%= link_to user.name, user %></h3>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %> <%= link_to '+', new_quit_path(user_id: @user) %></h1>
<% @user.quits.each do |quit| %>
  <p><%= quit.text %>  <%= link_to 'Edit', edit_quit_path(quit) %></p>
<% end %>